global:
  stage: dev
  projectName: showcase-infrastructure-charts
  source:
    repoURL: https://github.com/iits-consulting/showcase-azure-gitops-infrastructure-charts.git
    targetRevision: working
    appsBasePath: stages/dev/showcase-infrastructure-charts/apps

predator:
  namespace: predator
traefik:
  namespace: routing
  ignoreDifferences:
    - kind: Service
      jsonPointers:
        - /metadata/annotations
cert-manager:
  namespace: cert-manager